# Generated by Django 3.0.8 on 2021-07-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=10)),
                ('detalle_habitacion', models.CharField(blank=True, max_length=100)),
                ('dias_estadia', models.CharField(blank=True, max_length=10)),
                ('datos_facturacion', models.CharField(blank=True, max_length=100)),
                ('identificacion_cliente', models.CharField(blank=True, max_length=100)),
                ('moto_pago', models.CharField(blank=True, max_length=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
